### ISSUE TITLE
Blurred View disappears when button pressed.

### ISSUE THREAD

**Issue by Steven4294** [Adrian2112/UIImage-BlurredFrame#10]
I've declared a UIButton and set a blur view to the image, it everything works fine - however, as soon as i click on the button, the blur view disappears. How would I go about fixing this? Thanks in advance.

```
CGRect frame = CGRectMake(0, 0, 100, 20);

UIImage *img = self.ImageButton.imageView.image;
img = [img applyDarkEffectAtFrame:frame];
self.ImageButton.imageView.image = img;
```

**Comment by Adrian2112** [comment]
I think this has to do with the button and not with the image
You have to use the `setImage:forState:` method

https://developer.apple.com/library/ios/documentation/uikit/reference/UIButton_Class/UIButton/UIButton.html#//apple_ref/occ/instm/UIButton/setImage:forState:
