### ISSUE TITLE
Retina Images

### ISSUE THREAD

**Issue by ghost** [Adrian2112/UIImage-BlurredFrame#5]
looks and works great, but if i load an image by [UIImage imageNamed:@"image"] and in the image assets i have image.png and image@2x.png it doesn't work with a retina device

changing the croppedImageAtFrame to this works for retina and non retina images
- (UIImage *)croppedImageAtFrame:(CGRect)frame {
  frame = CGRectMake(frame.origin.x \* self.scale,
                     frame.origin.y \* self.scale,
                     frame.size.width \* self.scale,
                     frame.size.height \* self.scale);
  CGImageRef sourceImageRef = [self CGImage];
  CGImageRef newImageRef = CGImageCreateWithImageInRect(sourceImageRef, frame);
  UIImage *newImage = [UIImage imageWithCGImage:newImageRef scale:[self scale] orientation:[self imageOrientation]];
  CGImageRelease(newImageRef);
  return newImage;
  }

**Comment by Adrian2112** [comment]
Thank you.
I merged your change c39fde45884bc9e22c0ef168a0f0001c74a78d68
