### ISSUE TITLE
-[UIImage _isResizable]: message sent to deallocated instance 0x146e9940

### ISSUE THREAD

**Issue by liufsd** [Adrian2112/UIImage-BlurredFrame#6]
-[UIImage _isResizable]: message sent to deallocated instance 0x146e9940

when i relaunch my app, it will crash . why ? but not often .
if i relaunch second times after 1'm ,it will crash.that mean the image was release ???

**Comment by liufsd** [comment]
so. i just delete this line :[thumbImg release].
this is my old code.

**Comment by Adrian2112** [comment]
I don't understand... Is it working now?

**Comment by Adrian2112** [comment]
I will close this for now. If you still have a problem please post an issue an a descriptions
