### ISSUE TITLE
Undefined symbols for architecture armv7 - vImageBoxConvolve_ARGB8888

### ISSUE THREAD

**Issue by psilvatweasy** [Adrian2112/UIImage-BlurredFrame#7]
I'm having a build error and i don't know what is the problem.
Anyone can help me?

My valid Architectures are: "armv7, armv7s, i386"
And i'm using the Standard architectures.

Undefined symbols for architecture armv7:
  "_vImageBoxConvolve_ARGB8888", referenced from:
      -[UIImage(ImageEffects) applyBlurWithRadius:tintColor:saturationDeltaFactor:maskImage:] in UIImage+ImageEffects.o
  "_vImageMatrixMultiply_ARGB8888", referenced from:
      -[UIImage(ImageEffects) applyBlurWithRadius:tintColor:saturationDeltaFactor:maskImage:] in UIImage+ImageEffects.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by liufsd** [comment]
add lib .and run it success.
